version: "3.1"
services:
  mc:
    image: nextgenhealthcare/connect:4.5.1-custom
    build:
      context: .
    platform: linux/amd64
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://localhost:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
      - DISPLAY=$DISPLAY
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    depends_on:
      - db
    network_mode: host
    volumes:
      - "./appdata:/opt/connect/appdata"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  db:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432
    network_mode: host
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
